import {
  createStep,
  createWorkflow,
  StepResponse,
  transform,
  WorkflowResponse,
} from "@medusajs/framework/workflows-sdk"
import { createPromotionsWorkflow } from "@medusajs/medusa/core-flows"

import { FITMENT_DISCOUNT_PERCENT } from "../../lib/fitment-requests"
import { FITMENT_REQUEST_MODULE } from "../../modules/fitment-request"
import type FitmentRequestModuleService from "../../modules/fitment-request/service"

type SendFitmentDiscountInput = {
  fitment_request_id: string
  // Generated by the caller: workflow definitions must be deterministic.
  code: string
  vehicle: string
}

const markCodeSentStep = createStep(
  "mark-code-sent",
  async (input: { id: string; code: string }, { container }) => {
    const service = container.resolve<FitmentRequestModuleService>(
      FITMENT_REQUEST_MODULE
    )
    const updated = await service.updateFitmentRequests({
      id: input.id,
      status: "code_sent",
      discount_code: input.code,
    })

    return new StepResponse(updated, input.id)
  },
  async (id, { container }) => {
    if (!id) {
      return
    }
    await container
      .resolve<FitmentRequestModuleService>(FITMENT_REQUEST_MODULE)
      .updateFitmentRequests({ id, status: "new", discount_code: null })
  }
)

// Creates a single-use percentage code and records it on the request.
export const sendFitmentDiscountWorkflow = createWorkflow(
  "send-fitment-discount",
  (input: SendFitmentDiscountInput) => {
    const promotionsData = transform({ input }, ({ input }) => [
      {
        code: input.code,
        type: "standard" as const,
        status: "active" as const,
        is_automatic: false,
        limit: 1,
        application_method: {
          type: "percentage" as const,
          target_type: "order" as const,
          allocation: "across" as const,
          value: FITMENT_DISCOUNT_PERCENT,
        },
        metadata: {
          fitment_request_id: input.fitment_request_id,
          vehicle: input.vehicle,
        },
      },
    ])

    createPromotionsWorkflow.runAsStep({ input: { promotionsData } })

    const request = markCodeSentStep(
      transform({ input }, ({ input }) => ({
        id: input.fitment_request_id,
        code: input.code,
      }))
    )

    return new WorkflowResponse(request)
  }
)
